# Generated by Django 4.1.7 on 2023-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_menuitem_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='user3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('emails', models.EmailField(max_length=254)),
                ('pwds', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user3',
            },
        ),
    ]
