# Generated by Django 4.1.7 on 2023-07-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_adminuser_delete_user3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='name',
            new_name='pwd',
        ),
    ]
